/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BD.ExamenBD;
import BD.ImageBD;
import BD.PatientsBD;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sosso
 */
public class PHNormal extends javax.swing.JFrame {

    private File selFile;
    private BufferedImage image;

    public PHNormal() throws SQLException {
        initComponents();

        jTabbedPane1.setEnabledAt(1, false);


        image = null;
        selFile = null;
        ExamenBD exam = new ExamenBD();
        DefaultTableModel liste = new DefaultTableModel();
        liste.addColumn("IdPatient");
        liste.addColumn("Nom Patient");
        liste.addColumn("Prénom Patient");
        liste.addColumn("Sexe");
        liste.addColumn("Date de Naissance");
        liste.addColumn("IdExamen");
        liste.addColumn("Type d'examen");
        liste.addColumn("Date examen");
        liste.addColumn("Nom Practicien");
        liste.addColumn("Prénom Practicien");

        liste = exam.listeExam(liste);
        Tableau.setModel(liste);
        Tableau.setDefaultEditor(Object.class, null);
        Tableau.repaint();
        setIcone();

    }

    public void setIcone() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo Radiosistem2.jpeg")));

    }

    public JLabel getIdentifiantPro() {
        return identifiantPro;
    }

    public JLabel getNomPrenomUtilisateur() {
        return NomPrenomUtilisateur;
    }

    public JLabel getNomPrenomUtilisateur1() {
        return NomPrenomUtilisateur1;
    }



    public static BufferedImage rotateImage(BufferedImage imageToRotate) {
        int widthOfImage = imageToRotate.getWidth();
        int heightOfImage = imageToRotate.getHeight();
        int typeOfImage = imageToRotate.getType();

        BufferedImage newImageFromBuffer = new BufferedImage(widthOfImage, heightOfImage, typeOfImage);

        Graphics2D graphics2D = newImageFromBuffer.createGraphics();

        graphics2D.rotate(Math.toRadians(90), widthOfImage / 2, heightOfImage / 2);
        graphics2D.drawImage(imageToRotate, null, 0, 0);

        return newImageFromBuffer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Accueil = new javax.swing.JPanel();
        Principal = new javax.swing.JPanel();
        CritèreRecherchePannel = new javax.swing.JPanel();
        PanelListeEnsembleExamen = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ScrollTableau = new javax.swing.JScrollPane();
        Tableau = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        InfoPatient = new javax.swing.JPanel();
        NomPatient = new javax.swing.JLabel();
        PrenomPatient = new javax.swing.JLabel();
        TypeExamen = new javax.swing.JLabel();
        NomExamen = new javax.swing.JComboBox<String>();
        ChampNomPatient = new javax.swing.JTextField();
        ChampPrenomPatient = new javax.swing.JTextField();
        Rechercher = new javax.swing.JButton();
        idPatient = new javax.swing.JLabel();
        ChampIdPatient = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ConnecteEnTantQUE = new javax.swing.JLabel();
        NomPrenomUtilisateur = new javax.swing.JLabel();
        PanelListeEnsembleExamen1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        deconnexion = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        identifiantPro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ListeEnsembleExamen = new javax.swing.JLabel();
        ConsulterExamen = new javax.swing.JPanel();
        PanelHaut1 = new javax.swing.JPanel();
        ConnecteEnTantQue1 = new javax.swing.JLabel();
        NomPrenomUtilisateur1 = new javax.swing.JLabel();
        Retour2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeImage = new javax.swing.JList();
        jPanel11 = new javax.swing.JPanel();
        InfoPatient2 = new javax.swing.JPanel();
        Nom1 = new javax.swing.JLabel();
        Prenom1 = new javax.swing.JLabel();
        DateNaissance1 = new javax.swing.JLabel();
        Sexe1 = new javax.swing.JLabel();
        Adress1 = new javax.swing.JLabel();
        idPatient2 = new javax.swing.JLabel();
        ChampNom1 = new javax.swing.JLabel();
        ChampPrenom1 = new javax.swing.JLabel();
        ChampSexe1 = new javax.swing.JLabel();
        ChampAdresse = new javax.swing.JLabel();
        ChampDateNaissance = new javax.swing.JLabel();
        ChampIdPatient1 = new javax.swing.JLabel();
        InfoExamen1 = new javax.swing.JPanel();
        TypeExamen2 = new javax.swing.JLabel();
        ChampTypeExamen = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        ChampDate = new javax.swing.JFormattedTextField();
        PrenomPraticien = new javax.swing.JLabel();
        NomPraticien = new javax.swing.JLabel();
        ChampPrenomPraticien = new javax.swing.JLabel();
        ChampNomPraticien = new javax.swing.JLabel();
        idExamen = new javax.swing.JLabel();
        ChampIdExamen = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        CR1 = new javax.swing.JLabel();
        CR2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1751, 1371));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1751, 1371));
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabbedPane1PropertyChange(evt);
            }
        });

        Accueil.setBackground(new java.awt.Color(255, 255, 255));

        Principal.setBackground(new java.awt.Color(255, 255, 255));

        CritèreRecherchePannel.setBackground(new java.awt.Color(255, 255, 255));

        PanelListeEnsembleExamen.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout PanelListeEnsembleExamenLayout = new javax.swing.GroupLayout(PanelListeEnsembleExamen);
        PanelListeEnsembleExamen.setLayout(PanelListeEnsembleExamenLayout);
        PanelListeEnsembleExamenLayout.setHorizontalGroup(
            PanelListeEnsembleExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelListeEnsembleExamenLayout.setVerticalGroup(
            PanelListeEnsembleExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ScrollTableau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 2, true));
        ScrollTableau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Tableau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tableau.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idPatient", "Nom patient", "Prénom patient", "Sexe", "Date de naissance", "idExamen", "Type d'examen", "Date examen", "Nom praticien", "Prénom praticien"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tableau.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Tableau.setRowHeight(20);
        Tableau.getTableHeader().setReorderingAllowed(false);
        Tableau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableauMouseClicked(evt);
            }
        });
        ScrollTableau.setViewportView(Tableau);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollTableau, javax.swing.GroupLayout.PREFERRED_SIZE, 1321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ScrollTableau, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        InfoPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 2, true), "Critères de recherche", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N
        InfoPatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        NomPatient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomPatient.setText("Nom patient: ");

        PrenomPatient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PrenomPatient.setText("Prénom patient : ");

        TypeExamen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TypeExamen.setText("Type d'examen: ");

        NomExamen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NomExamen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "Mammographie", "Echographie", "Scanner", "Radiographie", " " }));
        NomExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomExamenActionPerformed(evt);
            }
        });

        ChampNomPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChampNomPatientActionPerformed(evt);
            }
        });

        Rechercher.setBackground(new java.awt.Color(204, 255, 204));
        Rechercher.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });

        idPatient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        idPatient.setText("idPatient:");

        javax.swing.GroupLayout InfoPatientLayout = new javax.swing.GroupLayout(InfoPatient);
        InfoPatient.setLayout(InfoPatientLayout);
        InfoPatientLayout.setHorizontalGroup(
            InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InfoPatientLayout.createSequentialGroup()
                        .addComponent(NomPatient)
                        .addGap(23, 23, 23)
                        .addComponent(ChampNomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InfoPatientLayout.createSequentialGroup()
                                .addComponent(TypeExamen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(InfoPatientLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Rechercher)
                                .addGap(26, 26, 26))))
                    .addGroup(InfoPatientLayout.createSequentialGroup()
                        .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(InfoPatientLayout.createSequentialGroup()
                                .addComponent(PrenomPatient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChampPrenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InfoPatientLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(idPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChampIdPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(577, 577, 577))))
        );
        InfoPatientLayout.setVerticalGroup(
            InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPatientLayout.createSequentialGroup()
                .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPatientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomPatient)
                            .addComponent(ChampNomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InfoPatientLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypeExamen)
                            .addComponent(NomExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrenomPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChampPrenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPatientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChampIdPatient))
                        .addGap(30, 30, 30))
                    .addGroup(InfoPatientLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Rechercher)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(InfoPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AJOUTEREXAMEN.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel6)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CritèreRecherchePannelLayout = new javax.swing.GroupLayout(CritèreRecherchePannel);
        CritèreRecherchePannel.setLayout(CritèreRecherchePannelLayout);
        CritèreRecherchePannelLayout.setHorizontalGroup(
            CritèreRecherchePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CritèreRecherchePannelLayout.createSequentialGroup()
                .addGap(1005, 1005, 1005)
                .addComponent(PanelListeEnsembleExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CritèreRecherchePannelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CritèreRecherchePannelLayout.setVerticalGroup(
            CritèreRecherchePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CritèreRecherchePannelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(CritèreRecherchePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelListeEnsembleExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ConnecteEnTantQUE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ConnecteEnTantQUE.setText("Connecté en tant que :");

        NomPrenomUtilisateur.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NomPrenomUtilisateur.setText("Seuad Kassa");

        PanelListeEnsembleExamen1.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout PanelListeEnsembleExamen1Layout = new javax.swing.GroupLayout(PanelListeEnsembleExamen1);
        PanelListeEnsembleExamen1.setLayout(PanelListeEnsembleExamen1Layout);
        PanelListeEnsembleExamen1Layout.setHorizontalGroup(
            PanelListeEnsembleExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelListeEnsembleExamen1Layout.setVerticalGroup(
            PanelListeEnsembleExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        deconnexion.setBackground(new java.awt.Color(204, 255, 204));
        deconnexion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deconnexion.setText("Déconnexion");
        deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        identifiantPro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        identifiantPro.setText("0000000000");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Identifiant :");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        ListeEnsembleExamen.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ListeEnsembleExamen.setForeground(new java.awt.Color(255, 51, 0));
        ListeEnsembleExamen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListeEnsembleExamen.setText("Liste de l'ensemble des examens");
        ListeEnsembleExamen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(608, 608, 608)
                .addComponent(ListeEnsembleExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListeEnsembleExamen)
                .addContainerGap())
        );

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelListeEnsembleExamen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(identifiantPro, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deconnexion)
                        .addGap(89, 89, 89))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addGap(1157, 1157, 1157)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addComponent(ConnecteEnTantQUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomPrenomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addComponent(CritèreRecherchePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deconnexion)
                        .addGap(23, 23, 23))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConnecteEnTantQUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(NomPrenomUtilisateur)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(identifiantPro))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(PanelListeEnsembleExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(CritèreRecherchePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AccueilLayout = new javax.swing.GroupLayout(Accueil);
        Accueil.setLayout(AccueilLayout);
        AccueilLayout.setHorizontalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AccueilLayout.setVerticalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilLayout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
        );

        jTabbedPane1.addTab("Accueil", Accueil);

        ConsulterExamen.setBackground(new java.awt.Color(255, 255, 255));

        PanelHaut1.setBackground(new java.awt.Color(255, 255, 255));

        ConnecteEnTantQue1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ConnecteEnTantQue1.setText("Connecté en tant que:");

        NomPrenomUtilisateur1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NomPrenomUtilisateur1.setText("Seuad KASSA");

        Retour2.setBackground(new java.awt.Color(204, 255, 204));
        Retour2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Retour2.setText("Retour");
        Retour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));
        jPanel4.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        Titre.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Titre.setForeground(new java.awt.Color(255, 51, 0));
        Titre.setText("Consulter Examen");
        Titre.setToolTipText("");
        Titre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel7.setBackground(new java.awt.Color(255, 51, 0));
        jPanel7.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelHaut1Layout = new javax.swing.GroupLayout(PanelHaut1);
        PanelHaut1.setLayout(PanelHaut1Layout);
        PanelHaut1Layout.setHorizontalGroup(
            PanelHaut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHaut1Layout.createSequentialGroup()
                .addComponent(ConnecteEnTantQue1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NomPrenomUtilisateur1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Retour2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHaut1Layout.createSequentialGroup()
                .addComponent(Titre, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(673, 673, 673))
        );
        PanelHaut1Layout.setVerticalGroup(
            PanelHaut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHaut1Layout.createSequentialGroup()
                .addGroup(PanelHaut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHaut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConnecteEnTantQue1)
                        .addComponent(NomPrenomUtilisateur1))
                    .addGroup(PanelHaut1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Retour2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Titre)
                .addGap(16, 16, 16)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        listeImage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        listeImage.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listeImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeImageMouseClicked(evt);
            }
        });
        listeImage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listeImageKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listeImage);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        InfoPatient2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 2, true), "Informations Patient", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        Nom1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nom1.setText("Nom :");

        Prenom1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Prenom1.setText("Prénom :");

        DateNaissance1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DateNaissance1.setText("Date de naissance :");

        Sexe1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sexe1.setText("Sexe :");

        Adress1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Adress1.setText("Adresse :");

        idPatient2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        idPatient2.setText("idPatient :");

        ChampNom1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampNom1.setText("NomPatient");

        ChampPrenom1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampPrenom1.setText("PrénomPatient");

        ChampSexe1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampSexe1.setText("Féminin");

        ChampAdresse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampAdresse.setText("3 rue des Violettes 38000 Grenoble");

        ChampDateNaissance.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampDateNaissance.setText("jLabel1");

        ChampIdPatient1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampIdPatient1.setText("idPatient");

        javax.swing.GroupLayout InfoPatient2Layout = new javax.swing.GroupLayout(InfoPatient2);
        InfoPatient2.setLayout(InfoPatient2Layout);
        InfoPatient2Layout.setHorizontalGroup(
            InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPatient2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPatient2Layout.createSequentialGroup()
                        .addComponent(DateNaissance1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChampDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPatient2Layout.createSequentialGroup()
                        .addComponent(Nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChampNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPatient2Layout.createSequentialGroup()
                        .addComponent(Prenom1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChampPrenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Sexe1)
                    .addComponent(idPatient2)
                    .addComponent(Adress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChampIdPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChampAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChampSexe1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        InfoPatient2Layout.setVerticalGroup(
            InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPatient2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPatient2Layout.createSequentialGroup()
                        .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nom1)
                            .addComponent(Sexe1)
                            .addComponent(ChampNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ChampSexe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adress1)
                    .addComponent(ChampPrenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChampAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateNaissance1)
                        .addComponent(ChampDateNaissance))
                    .addComponent(idPatient2)
                    .addComponent(ChampIdPatient1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        InfoExamen1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 2, true), "Informations examen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        TypeExamen2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TypeExamen2.setText("Type d'examen :");

        ChampTypeExamen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampTypeExamen.setText("Radio");

        Date.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Date.setText("Date :");

        ChampDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChampDateActionPerformed(evt);
            }
        });

        PrenomPraticien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PrenomPraticien.setText("Prénom praticien :");

        NomPraticien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomPraticien.setText("Nom praticien :");

        ChampPrenomPraticien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampPrenomPraticien.setText("Prénom praticien");

        ChampNomPraticien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampNomPraticien.setText("Nom praticien");

        idExamen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        idExamen.setText("idExamen :");

        ChampIdExamen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChampIdExamen.setText("idExamen");

        javax.swing.GroupLayout InfoExamen1Layout = new javax.swing.GroupLayout(InfoExamen1);
        InfoExamen1.setLayout(InfoExamen1Layout);
        InfoExamen1Layout.setHorizontalGroup(
            InfoExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoExamen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoExamen1Layout.createSequentialGroup()
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChampDate, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InfoExamen1Layout.createSequentialGroup()
                        .addComponent(TypeExamen2)
                        .addGap(8, 8, 8)
                        .addComponent(ChampTypeExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChampIdExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(InfoExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoExamen1Layout.createSequentialGroup()
                        .addComponent(NomPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChampNomPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoExamen1Layout.createSequentialGroup()
                        .addComponent(PrenomPraticien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChampPrenomPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        InfoExamen1Layout.setVerticalGroup(
            InfoExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoExamen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeExamen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChampTypeExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrenomPraticien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChampPrenomPraticien)
                    .addComponent(idExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChampIdExamen))
                .addGap(18, 18, 18)
                .addGroup(InfoExamen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(ChampDate)
                    .addComponent(NomPraticien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChampNomPraticien))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(InfoPatient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(InfoExamen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(InfoExamen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InfoPatient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/COMPTERENDU.png"))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel5)
                .addGap(109, 109, 109))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(48, 48, 48))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        CR1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CR1.setForeground(new java.awt.Color(255, 51, 0));
        CR1.setText("Compte-rendu");

        CR2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CR2.setForeground(new java.awt.Color(255, 51, 0));
        CR2.setText("Liste des images");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(CR1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CR2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CR1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CR2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout ConsulterExamenLayout = new javax.swing.GroupLayout(ConsulterExamen);
        ConsulterExamen.setLayout(ConsulterExamenLayout);
        ConsulterExamenLayout.setHorizontalGroup(
            ConsulterExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHaut1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ConsulterExamenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ConsulterExamenLayout.setVerticalGroup(
            ConsulterExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsulterExamenLayout.createSequentialGroup()
                .addComponent(PanelHaut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ConsulterExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsulterExamenLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsulterExamenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsulterExamenLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulter un examen", ConsulterExamen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        Connexion a = new Connexion();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deconnexionActionPerformed

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
         String nomPat = ChampNomPatient.getText().toUpperCase();
        String prenomPat = ChampPrenomPatient.getText();
        String idPat = ChampIdPatient.getText().toString();
        String type = NomExamen.getSelectedItem().toString();

        //Recherche par nom et prenom du patient
        if ((!nomPat.equals("")) && (!prenomPat.equals("")) && (idPat.equals("")) && (type.equals("  "))) {
            ExamenBD exam = null;

            try {
                exam = new ExamenBD();
            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }

            DefaultTableModel liste = new DefaultTableModel();

            liste.addColumn("IdPatient");
            liste.addColumn("Nom Patient");
            liste.addColumn("Prénom Patient");
            liste.addColumn("Sexe");
            liste.addColumn("Date de Naissance");
            liste.addColumn("IdExamen");
            liste.addColumn("Type d'examen");
            liste.addColumn("Date examen");
            liste.addColumn("Nom Practicien");
            liste.addColumn("Prénom Practicien");

            try {
                liste = exam.rechExamNomPrenom(prenomPat, nomPat, liste);
                System.out.println(liste);
            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }
            Tableau.setModel(liste);
            Tableau.repaint();

            //JOptionPane.showMessageDialog(this, "Examen trouvé");
        }

        //Recherche par nom prenom id
        if ((!nomPat.equals("")) && (!prenomPat.equals("")) && (!idPat.equals("")) && (type.equals("  "))) {
            ExamenBD exam = null;

            try {
                exam = new ExamenBD();
            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }

            DefaultTableModel liste = new DefaultTableModel();
            liste.addColumn("IdPatient");
            liste.addColumn("Nom Patient");
            liste.addColumn("Prénom Patient");
            liste.addColumn("Sexe");
            liste.addColumn("Date de Naissance");
            liste.addColumn("IdExamen");
            liste.addColumn("Type d'examen");
            liste.addColumn("Date examen");
            liste.addColumn("Nom Practicien");
            liste.addColumn("Prénom Practicien");

            try {
                liste = exam.rechExamNomPrenomId(idPat, prenomPat, nomPat, liste);
                System.out.println(liste);

            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(prenomPat);
            Tableau.setModel(liste);
            Tableau.repaint();
            System.out.println(prenomPat);

            //JOptionPane.showMessageDialog(this, "Examen trouvé");
        }

        //Recherche par nom prenom id type
        if ((!nomPat.equals("")) && (!prenomPat.equals("")) && (!idPat.equals("")) && (!type.equals("  "))) {
            ExamenBD exam = null;

            try {
                exam = new ExamenBD();
            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }

            DefaultTableModel liste = new DefaultTableModel();
            liste.addColumn("IdPatient");
            liste.addColumn("Nom Patient");
            liste.addColumn("Prénom Patient");
            liste.addColumn("Sexe");
            liste.addColumn("Date de Naissance");
            liste.addColumn("IdExamen");
            liste.addColumn("Type d'examen");
            liste.addColumn("Date examen");
            liste.addColumn("Nom Practicien");
            liste.addColumn("Prénom Practicien");

            try {
                //liste= exam.rechExamNomPrenomIdType(idPat,prenomPat, nomPat,type, liste);
                liste = exam.rechExamNomPrenomIdType(idPat, prenomPat, nomPat, type, liste);
                System.out.println("nom prenom id type " + liste);
                System.out.println(liste);
            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }
            Tableau.setModel(liste);
            Tableau.repaint();

            //JOptionPane.showMessageDialog(this, "Examen trouvé");
        }

    }//GEN-LAST:event_RechercherActionPerformed

    private void ChampDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChampDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChampDateActionPerformed

    private void Retour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Retour2ActionPerformed

    private void TableauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauMouseClicked
        if (evt.getClickCount() == 2) { // détection du double clique
            JTable cible = (JTable) evt.getSource();
            int ligne = cible.getSelectedRow(); //ligne du tableau sélectionnée.
            int col = Tableau.getColumnCount();
            //System.out.println(col);
            String idPat = Tableau.getValueAt(ligne, col - 10).toString();
            String nomPat = Tableau.getValueAt(ligne, col - 9).toString();
            String prenomPat = Tableau.getValueAt(ligne, col - 8).toString();
            String sexe = Tableau.getValueAt(ligne, col - 7).toString();
            String dateN = Tableau.getValueAt(ligne, col - 6).toString();
            String idExam = Tableau.getValueAt(ligne, col - 5).toString();
            String type = Tableau.getValueAt(ligne, col - 4).toString();
            String dateE = Tableau.getValueAt(ligne, col - 3).toString();
            String nomPro = Tableau.getValueAt(ligne, col - 2).toString();
            String prenomPro = Tableau.getValueAt(ligne, col - 1).toString();

            jTabbedPane1.setSelectedIndex(1);
            ChampNom1.setText(nomPat);
            ChampPrenom1.setText(prenomPat);
            ChampSexe1.setText(sexe);
            //ChampAdresse
            ChampDateNaissance.setText(dateN);
            ChampIdPatient1.setText(idPat);
            ChampTypeExamen.setText(type);
            ChampDate.setText(dateE);
            ChampPrenomPraticien.setText(prenomPro);
            ChampNomPraticien.setText(nomPro);
            ChampIdExamen.setText(idExam);

            PatientsBD pbd = null;
            try {
                pbd = new PatientsBD();
            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                ChampAdresse.setText(pbd.recupAdresse(idPat));
            } catch (SQLException ex) {
                Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
            }

            ExamenBD exam = null;
            String compteRendu = "";
            try {
                exam = new ExamenBD();

                //JOptionPane.showMessageDialog(null, prenomPro);
            } catch (SQLException ex) {
                Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                compteRendu = exam.recupContenuCR1(idExam);
            } catch (SQLException ex) {
                Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTextArea2.setText(compteRendu);
            jTextArea2.repaint();

            //liste des images de l'examen
            ImageBD i = null;
            i = new ImageBD();
            DefaultListModel l = null;
            try {
                l = i.listImage(ChampIdExamen.getText());
            } catch (SQLException ex) {
                Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
            }
            listeImage.setModel(l);

        }
    }//GEN-LAST:event_TableauMouseClicked

    private void listeImageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listeImageKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listeImageKeyPressed

    private void listeImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeImageMouseClicked
        if (evt.getClickCount() == 1) {
            String numString = listeImage.getSelectedValue().toString();
            System.out.println("num " + numString);
            int num = Integer.parseInt(numString);

            ImageBD i = null;
            i = new ImageBD();
            InputStream image = null;
            try {
                image = i.recupImage(num);
            } catch (SQLException ex) {
                Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedImage imageAffichage = null;
            try {
                imageAffichage = ImageIO.read(image);
            } catch (IOException ex) {
                Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
            }
            //ouverture de l'image sélectionnée
            JDialog d = new JDialog(this, "Image sélectionnée");
            d.setSize(300, 300);

            JLabel l = new JLabel("Ceci est une boite de dialogue.");
            // Ajouter l'étiquette à la boîte de dialogue 
            d.add(l);
            d.setLocation(650, 400);

            JLabel label = new JLabel(new ImageIcon(imageAffichage));
            d.add(label);

            d.setVisible(true);

        }
    }//GEN-LAST:event_listeImageMouseClicked

    private void jTabbedPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1PropertyChange

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        ExamenBD exam = null;
        
        try {
            exam = new ExamenBD();
        } catch (SQLException ex) {
            Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel liste = new DefaultTableModel();
        liste.addColumn("IdPatient");
        liste.addColumn("Nom Patient");
        liste.addColumn("Prénom Patient");
        liste.addColumn("Sexe");
        liste.addColumn("Date de Naissance");
        liste.addColumn("IdExamen");
        liste.addColumn("Type d'examen");
        liste.addColumn("Date examen");
        liste.addColumn("Nom Practicien");
        liste.addColumn("Prénom Practicien");

        try {
            liste = exam.listeExam(liste);
        } catch (SQLException ex) {
            Logger.getLogger(PHRadio.class.getName()).log(Level.SEVERE, null, ex);
        }
        Tableau.setModel(liste);

        Tableau.repaint();
        ChampNomPatient.setText("");
        ChampPrenomPatient.setText("");
        ChampIdPatient.setText("");
        NomExamen.setSelectedIndex(0);
     
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void NomExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomExamenActionPerformed


    }//GEN-LAST:event_NomExamenActionPerformed

    private void ChampNomPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChampNomPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChampNomPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new PHNormal().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PHNormal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JLabel Adress1;
    private javax.swing.JLabel CR1;
    private javax.swing.JLabel CR2;
    private javax.swing.JLabel ChampAdresse;
    private javax.swing.JFormattedTextField ChampDate;
    private javax.swing.JLabel ChampDateNaissance;
    private javax.swing.JLabel ChampIdExamen;
    private javax.swing.JTextField ChampIdPatient;
    private javax.swing.JLabel ChampIdPatient1;
    private javax.swing.JLabel ChampNom1;
    private javax.swing.JTextField ChampNomPatient;
    private javax.swing.JLabel ChampNomPraticien;
    private javax.swing.JLabel ChampPrenom1;
    private javax.swing.JTextField ChampPrenomPatient;
    private javax.swing.JLabel ChampPrenomPraticien;
    private javax.swing.JLabel ChampSexe1;
    private javax.swing.JLabel ChampTypeExamen;
    private javax.swing.JLabel ConnecteEnTantQUE;
    private javax.swing.JLabel ConnecteEnTantQue1;
    private javax.swing.JPanel ConsulterExamen;
    private javax.swing.JPanel CritèreRecherchePannel;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DateNaissance1;
    private javax.swing.JPanel InfoExamen1;
    private javax.swing.JPanel InfoPatient;
    private javax.swing.JPanel InfoPatient2;
    private javax.swing.JLabel ListeEnsembleExamen;
    private javax.swing.JLabel Nom1;
    private javax.swing.JComboBox<String> NomExamen;
    private javax.swing.JLabel NomPatient;
    private javax.swing.JLabel NomPraticien;
    private javax.swing.JLabel NomPrenomUtilisateur;
    private javax.swing.JLabel NomPrenomUtilisateur1;
    private javax.swing.JPanel PanelHaut1;
    private javax.swing.JPanel PanelListeEnsembleExamen;
    private javax.swing.JPanel PanelListeEnsembleExamen1;
    private javax.swing.JLabel Prenom1;
    private javax.swing.JLabel PrenomPatient;
    private javax.swing.JLabel PrenomPraticien;
    private javax.swing.JPanel Principal;
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton Retour2;
    private javax.swing.JScrollPane ScrollTableau;
    private javax.swing.JLabel Sexe1;
    private javax.swing.JTable Tableau;
    private javax.swing.JLabel Titre;
    private javax.swing.JLabel TypeExamen;
    private javax.swing.JLabel TypeExamen2;
    private javax.swing.JButton deconnexion;
    private javax.swing.JLabel idExamen;
    private javax.swing.JLabel idPatient;
    private javax.swing.JLabel idPatient2;
    private javax.swing.JLabel identifiantPro;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList listeImage;
    // End of variables declaration//GEN-END:variables
}
